server:
  port: 8091
spring:
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, api_platform
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
  application:
    name: api-platform-gateway
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
dubbo:
  application:
    name: api-platform-backend
  protocol:
    name: dubbo
    port: -1
  registry:
    id: -registry
    address: nacos://localhost:8848
nacos:
  discovery:
    server-addr: localhost:8848